In [42]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,precision_score, confusion_matrix,recall_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
data = pd.read_csv('Iris.csv');
# data.head()
le = LabelEncoder()
data["Species"] = le.fit_transform(data["Species"]);
X=data.drop("Species",axis=1)
Y=data["Species"];

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.5, random_state=42)

model = KNeighborsClassifier(n_neighbors=5);
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("knn model - performance");
print("accuracy score :",accuracy_score(y_test,y_pred))
print("confusion matrix :", confusion_matrix(y_test,y_pred))

knn model - performance
accuracy score : 1.0
confusion matrix : [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]


Logistic Regression


In [45]:
print("Logistic Regression model - performance");
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("accuracy score :",accuracy_score(y_test,y_pred))
print("confusion matrix :", confusion_matrix(y_test,y_pred))


Logistic Regression model - performance
accuracy score : 1.0
confusion matrix : [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]


In [46]:
print("Navie Bayes  model - performance");
model = GaussianNB();
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("accuracy score :",accuracy_score(y_test,y_pred))
print("confusion matrix :", confusion_matrix(y_test,y_pred))

Navie Bayes  model - performance
accuracy score : 1.0
confusion matrix : [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
